# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20160925_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='visible',
            field=models.CharField(default='SI', max_length=2),
        ),
    ]
