# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import entradas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0006_auto_20160925_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150)),
                ('texto_corto', models.CharField(max_length=255)),
                ('texto_largo', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=entradas.models.media_url)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('modificado_el', models.DateTimeField(auto_now=True)),
                ('visible', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=2)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blogs')),
            ],
        ),
    ]
