# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0002_post_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
