# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_auto_20160925_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='visible',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=2),
        ),
    ]
